export interface FunnelInputs {
  monthlyAdsBudget: number;
  estimatedReach: number;
  ctr: number; // 0..1
  landingConversionRate: number; // 0..1
  sqlRate: number; // 0..1
  closeRate: number; // 0..1
  averageTicket: number;
}

export interface FunnelOutputs {
  clicks: number;
  leads: number;
  sqls: number;
  sales: number;
  revenue: number;
  roas: number;
  cpl: number;
  costPerSale: number;
}

export type PhaseStatus = 'not_started' | 'in_progress' | 'completed' | 'delayed' | 'blocked';

export interface GanttSubtask {
  id: string;
  name: string;
  done: boolean;
}

export interface GanttTask {
  id: string;
  name: string;
  startWeek: number;
  endWeek: number;
  status: PhaseStatus;
  subtasks: GanttSubtask[];
}

export interface ProjectPhase {
  id: string;
  name: string;
  startWeek: number;
  endWeek: number;
  status: PhaseStatus;
  /**
   * Tareas estructuradas con subtareas. Mantenemos compatibilidad con la versión
   * anterior que sólo guardaba descripciones — al cargar un phase legacy, se
   * convierte automáticamente a esta forma con tareas vacías de subtasks.
   */
  tasks: GanttTask[];
  progress: number; // 0..100 — derivado de subtasks completadas si hay
}

export interface OKR {
  id: string;
  objective: string;
  deadline: string;
  responsible: string;
  keyResults: KeyResult[];
}

export type AdMetricKind = 'roas' | 'cpl' | 'cpc' | 'ctr' | 'leads' | 'sales' | 'revenue' | 'spend' | 'reach' | 'other';

export interface KeyResult {
  id: string;
  description: string;
  initialValue: number;
  targetValue: number;
  currentValue: number;
  unit: 'USD' | '%' | 'count' | 'ROAS';
  linkedToMetric?: AdMetricKind;
  // Histórico opcional para la mini-gráfica proyección vs real
  monthlyActuals?: number[];
}

export interface InvestmentLine {
  id: string;
  category: string;
  monthly: number;
  onlyMonths?: number[]; // si es activa sólo en meses específicos (ej. desarrollo en mes 1-2)
}

export interface MarketSizing {
  tam: number;
  sam: number;
  somPercent: number; // % del SAM
}

export interface DebriefingSections {
  executiveSummary?: { text: string; autoGenerated: boolean };
  context?: { situation: string; challenges: string; opportunities: string; swot: { s: string; w: string; o: string; t: string } };
  idealClient?: { text: string; autoGenerated: boolean };
  valueProp?: { text: string; bigIdea: string; guarantees: string };
  communication?: { text: string; tone: string; angles: string[] };
  salesSystem?: { text: string; funnel: string; stack: string };
  successMetrics?: { kpis: Array<{ name: string; frequency: string; owner: string; alertThreshold: string }> };
  team?: { text: string; raci: Array<{ task: string; responsible: string; accountable: string; consulted: string; informed: string }> };
  timeline?: { text: string; nextMilestones: Array<{ title: string; date: string }> };
  agreements?: { agencyDelivers: string; clientProvides: string; approvalTimes: string; conditions: string };
  appendices?: { competitorAnalysis: string; references: string; techStack: string; budget: string };
}

export type ScenarioId = 'conservative' | 'realistic' | 'optimistic';

export interface ProjectionState {
  clientId: string;
  funnel: FunnelInputs;
  activeScenario: ScenarioId;
  phases: ProjectPhase[];
  okrs: OKR[];
  successIndicators: string[]; // 3 indicadores
  benchmarksOverride: Partial<Record<string, number>>; // overrides por métrica
  market: MarketSizing;
  investment: InvestmentLine[];
  durationMonths: number;
  debriefing: DebriefingSections;
}
