import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import {
  Sparkles, TrendingUp, Target as TargetIcon, GanttChartSquare, Scale, Compass,
  DollarSign, FileText, Download, Plus, Trash2, Pencil, Save, X, Check, Link2, ChevronDown, ChevronUp,
  ArrowUp, ArrowDown,
} from 'lucide-react';
import {
  ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip as RTooltip,
  PieChart, Pie, Cell, Legend, LineChart, Line, ComposedChart, Radar, RadarChart,
  PolarGrid, PolarAngleAxis, PolarRadiusAxis,
} from 'recharts';
import type { Client } from '@/types/client';
import type { FunnelInputs, OKR, ProjectPhase, KeyResult, InvestmentLine, AdMetricKind, ScenarioId } from '@/types/projection';
import { Modal } from '@/components/ui/Modal';
import { useProjectionStore, calculateFunnel, SCENARIO_META } from '@/store/useProjectionStore';
import { getBenchmark } from '@/services/benchmarks';
import { exportProjectionToPdf, exportDebriefingToPdf } from '@/services/projectionPdf';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Textarea } from '@/components/ui/Textarea';
import { Badge } from '@/components/ui/Badge';
import { Select } from '@/components/ui/Select';
import { toast } from '@/store/useToastStore';
import { withAlpha } from '@/utils/colorGenerator';
import { formatCurrency, formatNumber, formatPercent } from '@/utils/metricsCalculator';
import { cn } from '@/utils/cn';
import { format, parseISO, addWeeks } from 'date-fns';
import { es } from 'date-fns/locale';

type SubTab = 'summary' | 'funnel' | 'phases' | 'market' | 'okrs' | 'investment' | 'debriefing';

const SUB_TABS: Array<{ id: SubTab; label: string; icon: typeof Compass; letter: string }> = [
  { id: 'summary',     label: 'Resumen',           icon: Compass,            letter: 'A' },
  { id: 'funnel',      label: 'Funnel financiero', icon: TrendingUp,         letter: 'B' },
  { id: 'phases',      label: 'Fases & tiempos',   icon: GanttChartSquare,   letter: 'C' },
  { id: 'market',      label: 'Vs Mercado',        icon: Scale,              letter: 'D' },
  { id: 'okrs',        label: 'Objetivos / OKRs',  icon: TargetIcon,         letter: 'E' },
  { id: 'investment',  label: 'Inversión',         icon: DollarSign,         letter: 'F' },
  { id: 'debriefing',  label: 'Debriefing',        icon: FileText,           letter: 'G' },
];

export function ProjectionsModule({ client }: { client: Client }) {
  const accent = client.primaryColor;
  const ensure = useProjectionStore((s) => s.ensure);
  const state = useProjectionStore((s) => s.states[client.id]);
  const [exporting, setExporting] = useState(false);
  const [active, setActive] = useState<SubTab>('summary');

  useEffect(() => {
    ensure(client.id, {
      projectType: client.projectType,
      funnel: {
        monthlyAdsBudget: client.monthlyAdsBudget,
        averageTicket: (client.onboardingData.business as { averageTicket?: number } | undefined)?.averageTicket ?? 0,
      } as Partial<FunnelInputs> as never,
      debriefing: {
        executiveSummary: client.aiBrainData.executiveSummary
          ? { text: client.aiBrainData.executiveSummary, autoGenerated: true }
          : undefined,
        valueProp: client.aiBrainData.irresistibleOffer
          ? { text: client.aiBrainData.irresistibleOffer, bigIdea: '', guarantees: '' }
          : undefined,
      },
    });
  }, [client.id, client.monthlyAdsBudget, client.projectType, client.aiBrainData.executiveSummary, client.aiBrainData.irresistibleOffer, client.onboardingData.business, ensure]);

  if (!state) return null;

  const handleExport = async () => {
    setExporting(true);
    try {
      await exportProjectionToPdf({ client, state });
      toast.success('PDF descargado');
    } catch (e) {
      console.error(e);
      toast.error('No pudimos generar el PDF');
    } finally {
      setExporting(false);
    }
  };

  return (
    <div className="space-y-4">
      {/* Header con tabs internos + botón PDF */}
      <div className="flex items-center justify-between gap-3 flex-wrap">
        <div className="surface p-1 flex items-center gap-0.5 overflow-x-auto">
          {SUB_TABS.map((t) => {
            const isActive = active === t.id;
            return (
              <button
                key={t.id}
                onClick={() => setActive(t.id)}
                className={cn(
                  'inline-flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs whitespace-nowrap transition focus-ring',
                  isActive ? 'text-text-primary' : 'text-text-secondary hover:text-text-primary',
                )}
                style={isActive ? { background: withAlpha(accent, 0.18) } : undefined}
              >
                <span className="text-[10px] font-mono text-text-muted">{t.letter}</span>
                <t.icon className="h-3.5 w-3.5" />
                <span className="font-medium">{t.label}</span>
              </button>
            );
          })}
        </div>
        <Button
          leftIcon={<Download className="h-4 w-4" />}
          loading={exporting}
          onClick={handleExport}
        >
          Descargar PDF
        </Button>
      </div>

      <motion.div
        key={active}
        initial={{ opacity: 0, y: 6 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.25 }}
      >
        {active === 'summary'    && <SummarySection client={client} accent={accent} />}
        {active === 'funnel'     && <FunnelSection client={client} accent={accent} />}
        {active === 'phases'     && <PhasesSection client={client} accent={accent} />}
        {active === 'market'     && <MarketSection client={client} accent={accent} />}
        {active === 'okrs'       && <OkrsSection client={client} accent={accent} />}
        {active === 'investment' && <InvestmentSection client={client} accent={accent} />}
        {active === 'debriefing' && <DebriefingSection client={client} accent={accent} />}
      </motion.div>
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════
   A — RESUMEN EJECUTIVO
   ═══════════════════════════════════════════════════════════════════════════ */

function SummarySection({ client, accent }: { client: Client; accent: string }) {
  const goals = client.onboardingData.goals as { revenue3m?: number; revenue6m?: number; revenue12m?: number; idealStartDate?: string } | undefined;
  const currentRevenueRange = (client.onboardingData.current as { monthlyRevenue?: string } | undefined)?.monthlyRevenue ?? 'sin definir';
  const state = useProjectionStore((s) => s.states[client.id]);
  const scenarioMeta = SCENARIO_META[state.activeScenario];

  const m3 = goals?.revenue3m ?? 0;
  const m6 = goals?.revenue6m ?? 0;
  const m12 = goals?.revenue12m ?? 0;
  const baseline = midOfRange(currentRevenueRange);

  const growth3m = baseline > 0 ? ((m3 - baseline) / baseline) * 100 : 0;
  const growth12m = baseline > 0 ? ((m12 - baseline) / baseline) * 100 : 0;

  const viability: 'green' | 'yellow' | 'red' =
    growth12m <= 200 ? 'green' : growth12m <= 500 ? 'yellow' : 'red';
  const viabilityLabel = viability === 'green' ? 'Alcanzable' : viability === 'yellow' ? 'Retador' : 'Muy agresivo';
  const viabilityHint =
    viability === 'green' ? 'El crecimiento proyectado está dentro de rangos típicos del sector.' :
    viability === 'yellow' ? 'Requiere ejecución muy fina y posiblemente inversión adicional.' :
    'Crecimiento por encima de benchmarks — revalidar metas con el cliente.';
  const viabilityColor = viability === 'green' ? '#10B981' : viability === 'yellow' ? '#F59E0B' : '#EF4444';

  const startDate = goals?.idealStartDate ? parseISO(goals.idealStartDate) : new Date();

  return (
    <div className="surface p-6 relative overflow-hidden">
      <div className="absolute -top-24 -right-24 h-64 w-64 rounded-full blur-3xl opacity-25" style={{ background: accent }} />
      <div className="relative">
        <div className="flex items-start justify-between gap-3 mb-5">
          <div>
            <div className="text-[10px] uppercase tracking-[0.22em] text-text-muted">
              Resumen ejecutivo
            </div>
            <h2 className="heading text-2xl font-bold mt-1">
              Proyección estratégica · <span style={{ color: accent }}>{client.name}</span>
            </h2>
          </div>
          <div className="flex items-center gap-3">
            <div
              className="rounded-[10px] border px-3 py-2"
              style={{ borderColor: withAlpha(scenarioMeta.tone, 0.4), background: withAlpha(scenarioMeta.tone, 0.10) }}
            >
              <div className="text-[10px] uppercase tracking-wider text-text-muted">Escenario activo</div>
              <div className="text-sm font-bold" style={{ color: scenarioMeta.tone }}>{scenarioMeta.label} · ×{scenarioMeta.factor}</div>
            </div>
            <div
              className="rounded-[10px] border px-4 py-2 text-center"
              style={{ borderColor: viabilityColor, background: withAlpha(viabilityColor, 0.10) }}
            >
              <div className="text-[10px] uppercase tracking-wider text-text-muted">Viabilidad</div>
              <div className="text-base font-bold" style={{ color: viabilityColor }}>{viabilityLabel}</div>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-5">
          <GoalCard label="Meta 3 meses" value={m3} growth={growth3m} baseline={baseline} accent={accent} />
          <GoalCard label="Meta 6 meses" value={m6} accent={accent} />
          <GoalCard label="Meta 12 meses" value={m12} growth={growth12m} baseline={baseline} accent={accent} highlight />
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
          <InfoMini label="Facturación actual (rango)" value={currentRevenueRange} />
          <InfoMini label="Inicio del proyecto" value={format(startDate, "d 'de' MMMM yyyy", { locale: es })} />
          <InfoMini label="Duración estimada" value={`${state.durationMonths} meses`} />
          <InfoMini label="Industria del cliente" value={client.industry} />
        </div>

        <p className="text-[12px] text-text-muted mt-4 leading-relaxed max-w-3xl">
          {viabilityHint}
        </p>
        <p className="text-[11px] mt-2" style={{ color: scenarioMeta.tone }}>
          Proyectando con escenario: <strong className="font-semibold">{scenarioMeta.label}</strong>. Cambia el escenario en la sección B · Funnel financiero.
        </p>
      </div>
    </div>
  );
}

function GoalCard({
  label, value, growth, baseline, accent, highlight,
}: {
  label: string;
  value: number;
  growth?: number;
  baseline?: number;
  accent: string;
  highlight?: boolean;
}) {
  return (
    <div
      className="surface p-5"
      style={highlight ? { borderColor: withAlpha(accent, 0.35), boxShadow: `0 0 24px -8px ${accent}` } : undefined}
    >
      <div className="text-[10px] uppercase tracking-wider text-text-muted">{label}</div>
      <div className="kpi-number mt-1.5" style={highlight ? { color: accent } : undefined}>
        {value > 0 ? formatCurrency(value) : '—'}
      </div>
      {growth !== undefined && baseline !== undefined && baseline > 0 && (
        <div className="text-[11px] text-text-muted mt-2">
          {growth > 0 ? '+' : ''}{growth.toFixed(0)}% vs hoy
        </div>
      )}
    </div>
  );
}

function InfoMini({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-[10px] border border-border-subtle bg-bg-base/30 p-3">
      <div className="text-[10px] uppercase tracking-wider text-text-muted">{label}</div>
      <div className="text-sm text-text-primary mt-0.5">{value}</div>
    </div>
  );
}

function midOfRange(s: string): number {
  const nums = s.match(/\d[\d.,]*/g)?.map((n) => Number(n.replace(/[.,]/g, ''))) ?? [];
  if (nums.length >= 2) return (nums[0] + nums[1]) / 2;
  if (nums.length === 1) return nums[0];
  return 0;
}

/* ═══════════════════════════════════════════════════════════════════════════
   B — FUNNEL FINANCIERO + ESCENARIOS
   ═══════════════════════════════════════════════════════════════════════════ */

function FunnelSection({ client, accent }: { client: Client; accent: string }) {
  const state = useProjectionStore((s) => s.states[client.id]);
  const patch = useProjectionStore((s) => s.patchFunnel);
  const f = state.funnel;
  const outputs = useMemo(() => calculateFunnel(f), [f]);

  const setActiveScenario = useProjectionStore((s) => s.setActiveScenario);
  const scenarios = useMemo(() => {
    return (Object.keys(SCENARIO_META) as ScenarioId[]).map((id) => {
      const meta = SCENARIO_META[id];
      const adjusted: FunnelInputs = {
        ...f,
        ctr: f.ctr * meta.factor,
        landingConversionRate: f.landingConversionRate * meta.factor,
        sqlRate: f.sqlRate * meta.factor,
        closeRate: f.closeRate * meta.factor,
      };
      const out = calculateFunnel(adjusted);
      return { id, ...meta, tone: id === 'realistic' ? accent : meta.tone, out };
    });
  }, [f, accent]);

  const growthData = [1, 2, 3, 6, 12].map((m) => ({
    label: `Mes ${m}`,
    revenue: Math.round(outputs.revenue * (m <= 3 ? 0.7 + (m - 1) * 0.15 : m === 6 ? 1.2 : 1.6)),
  }));

  return (
    <div className="space-y-4">
      <div className="surface p-5">
        <h3 className="heading text-base font-bold mb-1">Cuadro de proyecciones según resultados</h3>
        <p className="text-[11px] text-text-muted mb-4">
          Edita cualquier valor. El funnel y los outputs se recalculan en tiempo real.
        </p>

        <div className="grid grid-cols-1 lg:grid-cols-[1.2fr_1fr] gap-4">
          {/* Funnel editable */}
          <div className="space-y-2">
            <FunnelRow label="Inversión mensual en ADS" unit="USD" value={f.monthlyAdsBudget}
              onChange={(v) => patch(client.id, { monthlyAdsBudget: v })} accent={accent} />
            <FunnelRow label="Alcance estimado" unit="personas" value={f.estimatedReach}
              onChange={(v) => patch(client.id, { estimatedReach: v })} accent={accent} />
            <FunnelRow label="CTR esperado" unit="%" value={f.ctr * 100}
              onChange={(v) => patch(client.id, { ctr: v / 100 })} step="0.1" accent={accent} />
            <FunnelComputed label="Clics estimados" value={formatNumber(outputs.clicks)} accent={accent} />
            <FunnelRow label="Conversión landing" unit="%" value={f.landingConversionRate * 100}
              onChange={(v) => patch(client.id, { landingConversionRate: v / 100 })} step="0.1" accent={accent} />
            <FunnelComputed label="Leads estimados" value={`${formatNumber(outputs.leads)}/mes`} accent={accent} />
            <FunnelRow label="Tasa de calificación (SQL)" unit="%" value={f.sqlRate * 100}
              onChange={(v) => patch(client.id, { sqlRate: v / 100 })} step="1" accent={accent} />
            <FunnelComputed label="Leads calificados" value={`${formatNumber(outputs.sqls)} SQLs/mes`} accent={accent} />
            <FunnelRow label="Tasa de cierre" unit="%" value={f.closeRate * 100}
              onChange={(v) => patch(client.id, { closeRate: v / 100 })} step="1" accent={accent} />
            <FunnelComputed label="Ventas estimadas" value={`${formatNumber(outputs.sales)}/mes`} accent={accent} />
            <FunnelRow label="Ticket promedio" unit="USD" value={f.averageTicket}
              onChange={(v) => patch(client.id, { averageTicket: v })} accent={accent} />

            <div
              className="mt-2 rounded-[10px] p-4"
              style={{ background: withAlpha(accent, 0.10), border: `1px solid ${withAlpha(accent, 0.35)}` }}
            >
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <div className="text-[10px] uppercase tracking-wider text-text-muted">Facturación proyectada</div>
                  <div className="kpi-number" style={{ color: accent }}>{formatCurrency(outputs.revenue)}</div>
                </div>
                <div>
                  <div className="text-[10px] uppercase tracking-wider text-text-muted">ROAS</div>
                  <div className="kpi-number" style={{ color: accent }}>{outputs.roas}x</div>
                </div>
                <div>
                  <div className="text-[10px] uppercase tracking-wider text-text-muted">CPL</div>
                  <div className="text-lg font-semibold text-text-primary">{formatCurrency(outputs.cpl)}</div>
                </div>
                <div>
                  <div className="text-[10px] uppercase tracking-wider text-text-muted">Costo por venta</div>
                  <div className="text-lg font-semibold text-text-primary">{formatCurrency(outputs.costPerSale)}</div>
                </div>
              </div>
            </div>
          </div>

          {/* Gráfica de crecimiento */}
          <div>
            <div className="text-[10px] uppercase tracking-wider text-text-muted mb-2">
              Curva de facturación esperada
            </div>
            <div className="h-72">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={growthData}>
                  <CartesianGrid stroke="rgba(255,255,255,0.06)" strokeDasharray="3 3" />
                  <XAxis dataKey="label" stroke="#6B6B80" fontSize={11} />
                  <YAxis stroke="#6B6B80" fontSize={11} />
                  <RTooltip
                    contentStyle={{ background: '#12121A', border: '1px solid rgba(255,255,255,0.1)', borderRadius: 10, fontSize: 12 }}
                    formatter={(v: number) => formatCurrency(v)}
                  />
                  <Bar dataKey="revenue" fill={accent} radius={[6, 6, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
        </div>
      </div>

      {/* Escenarios — seleccionables */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
        {scenarios.map((s) => {
          const isActive = state.activeScenario === s.id;
          return (
            <button
              key={s.id}
              onClick={() => {
                setActiveScenario(client.id, s.id);
                toast.success(`Escenario ${s.label} seleccionado como objetivo del proyecto`);
              }}
              className={cn(
                'surface p-4 text-left transition-all focus-ring',
                isActive ? 'ring-2' : 'hover:bg-bg-elevated/30',
              )}
              style={{
                borderColor: isActive ? s.tone : withAlpha(s.tone, 0.35),
                boxShadow: isActive ? `0 0 24px -8px ${s.tone}` : undefined,
                ['--tw-ring-color' as string]: s.tone,
              }}
            >
              <div className="flex items-center gap-2 mb-3">
                <span className="h-2 w-2 rounded-full" style={{ background: s.tone, boxShadow: `0 0 10px ${s.tone}` }} />
                <h4 className="heading text-sm font-bold">{s.label}</h4>
                <span className="ml-auto text-[10px] text-text-muted">×{s.factor}</span>
              </div>
              {isActive && (
                <div className="mb-2 inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[9px] font-bold uppercase tracking-wider" style={{ background: withAlpha(s.tone, 0.18), color: s.tone, border: `1px solid ${withAlpha(s.tone, 0.4)}` }}>
                  <Check className="h-2.5 w-2.5" /> Objetivo activo
                </div>
              )}
              <div className="grid grid-cols-2 gap-2 text-sm">
                <Cell2 label="Leads" value={formatNumber(s.out.leads)} />
                <Cell2 label="Ventas" value={formatNumber(s.out.sales)} />
                <Cell2 label="Facturación" value={formatCurrency(s.out.revenue)} accent={s.tone} />
                <Cell2 label="ROAS" value={`${s.out.roas}x`} accent={s.tone} />
              </div>
            </button>
          );
        })}
      </div>
    </div>
  );
}

function Cell2({ label, value, accent }: { label: string; value: string; accent?: string }) {
  return (
    <div className="rounded-md border border-border-subtle bg-bg-base/30 p-2">
      <div className="text-[10px] uppercase tracking-wider text-text-muted">{label}</div>
      <div className="text-sm font-semibold" style={accent ? { color: accent } : { color: '#F5F5FA' }}>{value}</div>
    </div>
  );
}

function FunnelRow({
  label, unit, value, onChange, step = '1', accent,
}: {
  label: string;
  unit: string;
  value: number;
  onChange: (v: number) => void;
  step?: string;
  accent: string;
}) {
  return (
    <div className="grid grid-cols-[1.4fr_auto] gap-3 items-center rounded-[8px] border border-border-subtle bg-bg-base/30 px-3 py-2">
      <div className="text-xs text-text-secondary">
        {label}
        <span className="text-text-muted ml-1">({unit})</span>
      </div>
      <input
        type="number"
        value={value}
        step={step}
        onChange={(e) => onChange(Number(e.target.value))}
        className="w-32 bg-bg-elevated/60 border rounded-md px-2 py-1 text-sm text-right text-text-primary outline-none"
        style={{ borderColor: withAlpha(accent, 0.3), caretColor: accent }}
      />
    </div>
  );
}

function FunnelComputed({ label, value, accent }: { label: string; value: string; accent: string }) {
  return (
    <div
      className="grid grid-cols-[1.4fr_auto] gap-3 items-center rounded-[8px] px-3 py-1.5"
      style={{ background: withAlpha(accent, 0.06) }}
    >
      <div className="text-[11px] text-text-muted flex items-center gap-1">
        <span>→</span> {label}
      </div>
      <div className="text-sm font-semibold" style={{ color: accent }}>{value}</div>
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════
   C — FASES & TIEMPOS (Gantt)
   ═══════════════════════════════════════════════════════════════════════════ */

const PHASE_STATUS_LABEL: Record<ProjectPhase['status'], string> = {
  not_started: 'No iniciada',
  in_progress: 'En curso',
  completed: 'Completada',
  delayed: 'Retrasada',
  blocked: 'Bloqueada',
};

const PHASE_STATUS_COLOR: Record<ProjectPhase['status'], string> = {
  not_started: '#4B5563',
  in_progress: '', // se reemplaza por accent del cliente
  completed: '#10B981',
  delayed: '#EF4444',
  blocked: '#F59E0B',
};

function PhasesSection({ client, accent }: { client: Client; accent: string }) {
  const state = useProjectionStore((s) => s.states[client.id]);
  const setPhases = useProjectionStore((s) => s.setPhases);
  const phases = state.phases;
  const startDate = parseISO(
    (client.onboardingData.goals as { idealStartDate?: string } | undefined)?.idealStartDate ??
      new Date().toISOString().slice(0, 10),
  );
  const totalWeeks = Math.max(...phases.map((p) => p.endWeek));
  const [unit, setUnit] = useState<'weeks' | 'months'>('weeks');
  const [expandedPhases, setExpandedPhases] = useState<Set<string>>(new Set());
  const [expandedTasks, setExpandedTasks] = useState<Set<string>>(new Set());

  // % de avance de fase derivado de subtareas completadas
  const phaseProgress = (p: ProjectPhase) => {
    const all = p.tasks.flatMap((t) => t.subtasks);
    if (all.length === 0) return p.progress;
    const done = all.filter((s) => s.done).length;
    return Math.round((done / all.length) * 100);
  };

  const togglePhase = (id: string) => {
    setExpandedPhases((s) => {
      const n = new Set(s); n.has(id) ? n.delete(id) : n.add(id); return n;
    });
  };
  const toggleTask = (id: string) => {
    setExpandedTasks((s) => {
      const n = new Set(s); n.has(id) ? n.delete(id) : n.add(id); return n;
    });
  };

  const updatePhases = (next: ProjectPhase[]) => setPhases(client.id, next);

  const updateTaskInPhase = (phaseId: string, taskId: string, patch: Partial<import('@/types/projection').GanttTask>) => {
    updatePhases(phases.map((p) => p.id !== phaseId ? p : {
      ...p,
      tasks: p.tasks.map((t) => t.id === taskId ? { ...t, ...patch } : t),
    }));
  };
  const toggleSubtask = (phaseId: string, taskId: string, subId: string) => {
    updatePhases(phases.map((p) => p.id !== phaseId ? p : {
      ...p,
      tasks: p.tasks.map((t) => t.id !== taskId ? t : {
        ...t,
        subtasks: t.subtasks.map((s) => s.id === subId ? { ...s, done: !s.done } : s),
      }),
    }));
  };
  const addTaskToPhase = (phaseId: string) => {
    const phase = phases.find((p) => p.id === phaseId);
    if (!phase) return;
    updatePhases(phases.map((p) => p.id !== phaseId ? p : {
      ...p,
      tasks: [...p.tasks, { id: `gt_${Math.random().toString(36).slice(2,7)}`, name: 'Nueva tarea', startWeek: phase.startWeek, endWeek: phase.endWeek, status: 'not_started' as const, subtasks: [] }],
    }));
  };
  const addSubtaskToTask = (phaseId: string, taskId: string) => {
    updatePhases(phases.map((p) => p.id !== phaseId ? p : {
      ...p,
      tasks: p.tasks.map((t) => t.id !== taskId ? t : {
        ...t,
        subtasks: [...t.subtasks, { id: `gs_${Math.random().toString(36).slice(2,7)}`, name: 'Nueva subtarea', done: false }],
      }),
    }));
  };

  const headerLabels = unit === 'weeks'
    ? Array.from({ length: totalWeeks }).map((_, i) => i + 1)
    : Array.from({ length: Math.ceil(totalWeeks / 4) }).map((_, i) => i + 1);

  const colorFor = (status: ProjectPhase['status']) =>
    status === 'in_progress' ? accent : PHASE_STATUS_COLOR[status];

  return (
    <div className="surface p-5">
      <header className="flex items-center justify-between mb-4 flex-wrap gap-3">
        <div>
          <h3 className="heading text-base font-bold">Tiempos de ejecución por fases</h3>
          <p className="text-[11px] text-text-muted">
            {phases.length} fases · {totalWeeks} semanas · inicio {format(startDate, 'd MMM yyyy', { locale: es })}
          </p>
        </div>
        <div className="inline-flex rounded-[10px] border border-border-subtle bg-bg-base/40 p-0.5">
          <button onClick={() => setUnit('weeks')} className={cn('px-3 py-1.5 rounded-md text-xs', unit === 'weeks' ? 'bg-bg-elevated text-text-primary' : 'text-text-secondary')}>
            Semanas
          </button>
          <button onClick={() => setUnit('months')} className={cn('px-3 py-1.5 rounded-md text-xs', unit === 'months' ? 'bg-bg-elevated text-text-primary' : 'text-text-secondary')}>
            Meses
          </button>
        </div>
      </header>

      <div className="overflow-x-auto">
        <div className="min-w-[900px]">
          {/* Header de timeline */}
          <div className="grid grid-cols-[280px_1fr] gap-2 mb-2 sticky top-0 bg-bg-surface z-10">
            <div className="text-[10px] uppercase tracking-wider text-text-muted px-2">Fase / Tarea / Subtarea</div>
            <div className="grid gap-px text-[9px] text-text-muted" style={{ gridTemplateColumns: `repeat(${headerLabels.length}, minmax(0, 1fr))` }}>
              {headerLabels.map((n, i) => (
                <div key={i} className="text-center font-mono">
                  {unit === 'weeks' ? (((i+1) % 4 === 0 || i === 0 || i === headerLabels.length - 1) ? `S${n}` : '') : `M${n}`}
                </div>
              ))}
            </div>
          </div>

          {phases.map((p) => {
            const progress = phaseProgress(p);
            const open = expandedPhases.has(p.id);
            const span = p.endWeek - p.startWeek + 1;
            const ratio = (w: number) => ((w - 1) / totalWeeks) * 100;

            return (
              <div key={p.id} className="border-b border-border-subtle/40 py-1">
                {/* PHASE ROW */}
                <div className="grid grid-cols-[280px_1fr] gap-2 items-center group">
                  <div className="flex items-center gap-1 min-w-0 px-1 py-1 bg-bg-elevated/30 rounded-md">
                    <button onClick={() => togglePhase(p.id)} className="text-text-muted hover:text-text-primary shrink-0">
                      {open ? <ChevronDown className="h-3.5 w-3.5" /> : <ChevronUp className="h-3.5 w-3.5" />}
                    </button>
                    <div className="min-w-0 flex-1">
                      <div className="text-sm font-bold text-text-primary truncate" title={p.name}>{p.name}</div>
                      <div className="flex items-center gap-2 text-[9px] text-text-muted">
                        <span style={{ color: colorFor(p.status) }}>{PHASE_STATUS_LABEL[p.status]}</span>
                        <span>· {progress}%</span>
                        <span>· S{p.startWeek}–{p.endWeek}</span>
                      </div>
                    </div>
                    <button onClick={() => addTaskToPhase(p.id)} className="opacity-0 group-hover:opacity-100 text-text-muted hover:text-text-primary shrink-0" title="Agregar tarea">
                      <Plus className="h-3.5 w-3.5" />
                    </button>
                  </div>
                  <div className="relative h-3 rounded-md bg-bg-elevated/30">
                    <div
                      className="absolute top-0 bottom-0 rounded-md"
                      style={{
                        left: `${ratio(p.startWeek)}%`,
                        width: `${(span / totalWeeks) * 100}%`,
                        background: `linear-gradient(90deg, ${accent}, ${withAlpha(accent, 0.5)})`,
                        boxShadow: `0 0 10px -4px ${accent}`,
                      }}
                      title={`${p.name} · ${format(addWeeks(startDate, p.startWeek - 1), 'd MMM', { locale: es })} – ${format(addWeeks(startDate, p.endWeek - 1), 'd MMM', { locale: es })}`}
                    />
                  </div>
                </div>

                {/* TASKS */}
                {open && p.tasks.map((t) => {
                  const tOpen = expandedTasks.has(t.id);
                  const tSpan = t.endWeek - t.startWeek + 1;
                  const tColor = colorFor(t.status);
                  const tDone = t.subtasks.length > 0 ? t.subtasks.filter((s) => s.done).length : 0;
                  return (
                    <div key={t.id} className="ml-2">
                      <div className="grid grid-cols-[280px_1fr] gap-2 items-center group">
                        <div className="flex items-center gap-1 min-w-0 pl-4 py-1">
                          <button onClick={() => toggleTask(t.id)} className="text-text-muted hover:text-text-primary shrink-0">
                            {tOpen ? <ChevronDown className="h-3 w-3" /> : <ChevronUp className="h-3 w-3" />}
                          </button>
                          <div className="min-w-0 flex-1">
                            <div className="text-xs text-text-primary truncate" title={t.name}>{t.name}</div>
                            {t.subtasks.length > 0 && (
                              <div className="text-[9px] text-text-muted">{tDone}/{t.subtasks.length} subtareas</div>
                            )}
                          </div>
                          <button onClick={() => addSubtaskToTask(p.id, t.id)} className="opacity-0 group-hover:opacity-100 text-text-muted hover:text-text-primary shrink-0" title="Agregar subtarea">
                            <Plus className="h-3 w-3" />
                          </button>
                        </div>
                        <div className="relative h-2 rounded-md bg-bg-elevated/30">
                          <div
                            className="absolute top-0 bottom-0 rounded-md"
                            style={{
                              left: `${ratio(t.startWeek)}%`,
                              width: `${(tSpan / totalWeeks) * 100}%`,
                              background: tColor,
                            }}
                            title={`${t.name} · S${t.startWeek}–${t.endWeek} · ${PHASE_STATUS_LABEL[t.status]}`}
                          />
                        </div>
                      </div>

                      {/* SUBTASKS */}
                      {tOpen && t.subtasks.map((s) => {
                        return (
                          <div key={s.id} className="grid grid-cols-[280px_1fr] gap-2 items-center pl-10 py-0.5">
                            <label className="flex items-center gap-2 text-[11px] text-text-secondary cursor-pointer">
                              <input
                                type="checkbox"
                                checked={s.done}
                                onChange={() => toggleSubtask(p.id, t.id, s.id)}
                                className="h-3 w-3 accent-accent-violet"
                              />
                              <span className={cn('truncate', s.done && 'line-through text-text-muted')}>{s.name}</span>
                            </label>
                            <div className="relative h-1 rounded bg-bg-elevated/30">
                              <div
                                className="absolute top-0 bottom-0 rounded"
                                style={{
                                  left: `${ratio(t.startWeek)}%`,
                                  width: `${(tSpan / totalWeeks) * 100}%`,
                                  background: s.done ? '#10B981' : withAlpha(tColor, 0.4),
                                }}
                              />
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  );
                })}
              </div>
            );
          })}
        </div>
      </div>

      <div className="mt-4 flex items-center gap-3 flex-wrap text-[10px] text-text-muted">
        {(Object.keys(PHASE_STATUS_LABEL) as ProjectPhase['status'][]).map((s) => (
          <div key={s} className="flex items-center gap-1">
            <span className="h-2 w-3 rounded-sm" style={{ background: colorFor(s) }} />
            {PHASE_STATUS_LABEL[s]}
          </div>
        ))}
      </div>
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════
   D — VS MERCADO (benchmarks + sizing)
   ═══════════════════════════════════════════════════════════════════════════ */

function MarketSection({ client, accent }: { client: Client; accent: string }) {
  const bench = getBenchmark(client.industry);
  const state = useProjectionStore((s) => s.states[client.id]);
  const patchMarket = useProjectionStore((s) => s.patchMarket);
  const setOverride = useProjectionStore((s) => s.setBenchmarkOverride);
  const outputs = calculateFunnel(state.funnel);

  const rows = useMemo(() => [
    { key: 'ctrMeta',     label: 'CTR Meta Ads',       unit: '%', benchmark: bench.ctrMeta,     yours: state.funnel.ctr * 100,                higherBetter: true },
    { key: 'ctrGoogle',   label: 'CTR Google Ads',     unit: '%', benchmark: bench.ctrGoogle,   yours: state.funnel.ctr * 100,                higherBetter: true },
    { key: 'landingConv', label: 'Conversión landing', unit: '%', benchmark: bench.landingConv, yours: state.funnel.landingConversionRate * 100, higherBetter: true },
    { key: 'avgCpl',      label: 'CPL',                unit: '$', benchmark: bench.avgCpl,      yours: outputs.cpl,                            higherBetter: false },
    { key: 'avgRoas',     label: 'ROAS',               unit: 'x', benchmark: bench.avgRoas,     yours: outputs.roas,                            higherBetter: true },
    { key: 'closeRate',   label: 'Tasa de cierre',     unit: '%', benchmark: bench.closeRate,   yours: state.funnel.closeRate * 100,           higherBetter: true },
    { key: 'avgLtv',      label: 'LTV',                unit: '$', benchmark: bench.avgLtv,      yours: state.funnel.averageTicket,             higherBetter: true },
  ], [bench, state.funnel, outputs]);

  // Aplica override
  const rowsResolved = rows.map((r) => {
    const overridden = state.benchmarksOverride[r.key];
    const benchValue = overridden ?? r.benchmark;
    const diff = r.higherBetter ? ((r.yours - benchValue) / benchValue) * 100 : ((benchValue - r.yours) / benchValue) * 100;
    const status: 'excellent' | 'good' | 'improve' | 'critical' =
      diff >= 25 ? 'excellent' : diff >= 0 ? 'good' : diff >= -25 ? 'improve' : 'critical';
    return { ...r, benchValue, diff, status };
  });

  const statusMeta: Record<'excellent' | 'good' | 'improve' | 'critical', { label: string; tone: 'success' | 'info' | 'warning' | 'danger'; color: string }> = {
    excellent: { label: 'Excelente', tone: 'success', color: '#10B981' },
    good:      { label: 'Bien',      tone: 'info',    color: '#06B6D4' },
    improve:   { label: 'Mejorar',   tone: 'warning', color: '#F59E0B' },
    critical:  { label: 'Crítico',   tone: 'danger',  color: '#EF4444' },
  };

  const overallScore = Math.round(
    rowsResolved.reduce((s, r) => s + Math.max(0, Math.min(100, 50 + r.diff / 2)), 0) / rowsResolved.length,
  );

  // Datos para radar: normaliza cada métrica a 0..100 contra benchmark
  const radarData = rowsResolved.slice(0, 6).map((r) => {
    const youNorm = r.higherBetter
      ? Math.min(150, (r.yours / r.benchValue) * 100)
      : Math.min(150, (r.benchValue / Math.max(0.0001, r.yours)) * 100);
    return {
      metric: r.label,
      Tu_proyeccion: Math.max(0, Math.round(youNorm)),
      Benchmark: 100,
    };
  });

  const sizing = state.market;
  const som = (sizing.sam * sizing.somPercent) / 100;
  const shareYear1 = sizing.sam > 0 ? (outputs.sales * 12 / sizing.sam) * 100 : 0;

  return (
    <div className="space-y-4">
      {/* PARTE A — Scorecard */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
        {rowsResolved.slice(0, 4).map((r) => {
          const meta = statusMeta[r.status];
          const pct = r.higherBetter
            ? Math.min(150, (r.yours / r.benchValue) * 100)
            : Math.min(150, (r.benchValue / Math.max(0.0001, r.yours)) * 100);
          return (
            <div key={r.key} className="surface p-4">
              <div className="text-[10px] uppercase tracking-wider text-text-muted">{r.label}</div>
              <div className="flex items-baseline gap-2 mt-1">
                <span className="kpi-number" style={{ color: meta.color }}>
                  {r.unit === '$' ? `$${r.yours.toFixed(2)}` : `${r.yours.toFixed(2)}${r.unit}`}
                </span>
                {r.diff >= 0 ? <ArrowUp className="h-3.5 w-3.5 text-status-success" /> : <ArrowDown className="h-3.5 w-3.5 text-status-danger" />}
              </div>
              <div className="text-[10px] text-text-muted mt-1">
                Benchmark: {r.unit === '$' ? `$${r.benchValue.toFixed(2)}` : `${r.benchValue.toFixed(2)}${r.unit}`}
              </div>
              <div className="mt-2 h-1.5 rounded-full bg-bg-elevated overflow-hidden relative">
                <div
                  className="absolute top-0 bottom-0 left-0 rounded-full"
                  style={{ width: `${Math.min(100, pct)}%`, background: meta.color }}
                />
                {pct > 100 && (
                  <div
                    className="absolute top-0 bottom-0 rounded-full"
                    style={{ left: '100%', width: `${Math.min(50, pct - 100)}%`, background: '#10B981', opacity: 0.6 }}
                  />
                )}
              </div>
            </div>
          );
        })}
      </div>

      {/* PARTE B — Radar */}
      <div className="surface p-5">
        <header className="mb-3">
          <h3 className="heading text-base font-bold">Posición competitiva proyectada</h3>
          <p className="text-[11px] text-text-muted">Tu proyección vs benchmark de {client.industry} (100 = benchmark)</p>
        </header>
        <div className="h-80">
          <ResponsiveContainer width="100%" height="100%">
            <RadarChart data={radarData}>
              <PolarGrid stroke="rgba(255,255,255,0.08)" />
              <PolarAngleAxis dataKey="metric" tick={{ fill: '#A0A0B4', fontSize: 10 }} />
              <PolarRadiusAxis tick={{ fill: '#6B6B80', fontSize: 9 }} angle={90} domain={[0, 150]} />
              <Radar name="Benchmark" dataKey="Benchmark" stroke="#A0A0B4" fill="#A0A0B4" fillOpacity={0.18} />
              <Radar name="Tu proyección" dataKey="Tu_proyeccion" stroke={accent} fill={accent} fillOpacity={0.30} />
              <Legend wrapperStyle={{ fontSize: 11, color: '#A0A0B4' }} />
              <RTooltip
                contentStyle={{ background: 'rgba(15,15,25,0.95)', border: `1px solid ${accent}`, borderRadius: 10, fontSize: 12, color: '#FFFFFF' }}
              />
            </RadarChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* PARTE C — Tabla detallada */}
      <div className="surface p-5">
        <header className="flex items-center justify-between mb-3">
          <div>
            <h3 className="heading text-base font-bold">Detalle por métrica</h3>
            <p className="text-[11px] text-text-muted">Edita los benchmarks si tienes data más reciente</p>
          </div>
          <div className="rounded-[10px] border px-3 py-2 text-center" style={{ borderColor: accent, background: withAlpha(accent, 0.10) }}>
            <div className="text-[10px] uppercase tracking-wider text-text-muted">Posición general</div>
            <div className="text-lg font-bold" style={{ color: accent }}>{overallScore}/100</div>
          </div>
        </header>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-[10px] uppercase tracking-wider text-text-muted border-b border-border-default bg-bg-elevated/40">
                <th className="py-2 pl-2 pr-3">Métrica</th>
                <th className="py-2 pr-3 text-right">Benchmark</th>
                <th className="py-2 pr-3 text-right">Tu proyección</th>
                <th className="py-2 pr-3 text-right">Diferencia</th>
                <th className="py-2 pr-3 pr-2 text-center">Estado</th>
              </tr>
            </thead>
            <tbody>
              {rowsResolved.map((r, idx) => {
                const meta = statusMeta[r.status];
                return (
                  <tr key={r.key} className={cn('border-b border-border-subtle/30', idx % 2 === 1 && 'bg-bg-elevated/15')}>
                    <td className="py-2.5 pl-2 pr-3 text-text-primary">{r.label}</td>
                    <td className="py-2.5 pr-3 text-right">
                      <input
                        type="number"
                        defaultValue={r.benchValue}
                        step="0.1"
                        onBlur={(e) => {
                          const v = Number(e.target.value);
                          setOverride(client.id, r.key, v === r.benchmark ? undefined : v);
                        }}
                        className="w-24 bg-bg-elevated/40 border border-border-subtle rounded-md px-2 py-1 text-right text-text-primary outline-none text-xs"
                      />
                    </td>
                    <td className="py-2.5 pr-3 text-right font-semibold text-text-primary">
                      {r.unit === '$' ? `$${r.yours.toFixed(2)}` : `${r.yours.toFixed(2)}${r.unit}`}
                    </td>
                    <td className="py-2.5 pr-3 text-right font-semibold" style={{ color: r.diff >= 0 ? '#10B981' : '#EF4444' }}>
                      {r.diff >= 0 ? '+' : ''}{r.diff.toFixed(0)}%
                    </td>
                    <td className="py-2.5 pl-3 pr-2 text-center">
                      <Badge tone={meta.tone}>{meta.label}</Badge>
                    </td>
                  </tr>
                );
              })}
              <tr className="border-t-2 font-bold" style={{ background: withAlpha(accent, 0.10), borderColor: withAlpha(accent, 0.35) }}>
                <td className="py-2.5 pl-2 pr-3 text-text-primary uppercase text-[10px] tracking-wider">Posición general</td>
                <td colSpan={3} className="py-2.5 pr-3 text-right text-xs text-text-muted">Promedio ponderado</td>
                <td className="py-2.5 pl-3 pr-2 text-center" style={{ color: accent }}>{overallScore}/100</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div className="surface p-5">
        <h3 className="heading text-base font-bold mb-3">Tamaño de mercado</h3>
        <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
          <Input label="TAM (mercado total)" type="number" value={sizing.tam}
            onChange={(e) => patchMarket(client.id, { tam: Number(e.target.value) })} />
          <Input label="SAM (serviceable)" type="number" value={sizing.sam}
            onChange={(e) => patchMarket(client.id, { sam: Number(e.target.value) })} />
          <Input label="SOM (% del SAM)" type="number" step="0.1" value={sizing.somPercent}
            onChange={(e) => patchMarket(client.id, { somPercent: Number(e.target.value) })} />
          <div className="rounded-[10px] border bg-bg-base/30 p-3" style={{ borderColor: withAlpha(accent, 0.25) }}>
            <div className="text-[10px] uppercase tracking-wider text-text-muted">SOM calculado</div>
            <div className="text-lg font-bold" style={{ color: accent }}>{formatNumber(Math.round(som))} personas</div>
            <div className="text-[10px] text-text-muted mt-1">Cuota proyectada año 1: {shareYear1.toFixed(2)}%</div>
          </div>
        </div>
      </div>
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════════
   E — OKRs
   ═══════════════════════════════════════════════════════════════════════════ */

function OkrsSection({ client, accent }: { client: Client; accent: string }) {
  const state = useProjectionStore((s) => s.states[client.id]);
  const setOkrs = useProjectionStore((s) => s.setOkrs);
  const setSuccessIndicators = useProjectionStore((s) => s.setSuccessIndicators);
  const okrs = state.okrs;

  const updateOkr = (id: string, patch: Partial<OKR>) => {
    setOkrs(client.id, okrs.map((o) => (o.id === id ? { ...o, ...patch } : o)));
  };
  const updateKr = (okrId: string, krId: string, patch: Partial<KeyResult>) => {
    setOkrs(client.id, okrs.map((o) =>
      o.id !== okrId ? o : { ...o, keyResults: o.keyResults.map((k) => (k.id === krId ? { ...k, ...patch } : k)) },
    ));
  };
  const addKr = (okrId: string) => {
    setOkrs(client.id, okrs.map((o) =>
      o.id !== okrId ? o : {
        ...o,
        keyResults: [
          ...o.keyResults,
          { id: `kr_${Math.random().toString(36).slice(2, 6)}`, description: 'Nuevo Key Result', initialValue: 0, targetValue: 100, currentValue: 0, unit: 'count' },
        ].slice(0, 5),
      },
    ));
  };
  const removeKr = (okrId: string, krId: string) => {
    setOkrs(client.id, okrs.map((o) =>
      o.id !== okrId ? o : { ...o, keyResults: o.keyResults.filter((k) => k.id !== krId) },
    ));
  };

  return (
    <div className="space-y-4">
      {okrs.map((okr) => (
        <div key={okr.id} className="surface p-5">
          <div className="flex items-start gap-3 mb-4">
            <div
              className="h-9 w-9 rounded-[10px] flex items-center justify-center heading font-bold text-lg shrink-0"
              style={{ background: withAlpha(accent, 0.15), color: accent }}
            >
              O
            </div>
            <div className="flex-1 space-y-2">
              <Textarea
                rows={2}
                value={okr.objective}
                onChange={(e) => updateOkr(okr.id, { objective: e.target.value })}
                placeholder="Objetivo principal del proyecto…"
              />
              <div className="grid grid-cols-2 gap-3">
                <Input label="Deadline" type="date" value={okr.deadline} onChange={(e) => updateOkr(okr.id, { deadline: e.target.value })} />
                <Input label="Responsable" value={okr.responsible} onChange={(e) => updateOkr(okr.id, { responsible: e.target.value })} />
              </div>
            </div>
          </div>

          <div className="space-y-3">
            {okr.keyResults.map((kr) => (
              <KrCard
                key={kr.id}
                kr={kr}
                accent={accent}
                duration={state.durationMonths}
                onChange={(patch) => updateKr(okr.id, kr.id, patch)}
                onRemove={() => removeKr(okr.id, kr.id)}
                hasAdsData={Object.values(client.adsConnected).some(Boolean)}
              />
            ))}
            <button
              onClick={() => addKr(okr.id)}
              disabled={okr.keyResults.length >= 5}
              className="w-full rounded-[10px] border border-dashed border-border-default py-2 text-xs text-text-secondary hover:text-text-primary hover:bg-bg-elevated transition disabled:opacity-50"
            >
              <Plus className="h-3.5 w-3.5 inline mr-1" /> Agregar Key Result (máx 5)
            </button>
          </div>
        </div>
      ))}

      {/* Indicadores de éxito */}
      <div className="surface p-5">
        <h3 className="heading text-base font-bold mb-1">Indicadores de Éxito</h3>
        <p className="text-[11px] text-text-muted mb-3">¿Cómo sabremos que el proyecto fue un éxito?</p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          {[0, 1, 2].map((i) => (
            <Textarea
              key={i}
              rows={3}
              value={state.successIndicators[i] ?? ''}
              onChange={(e) => {
                const next = [...state.successIndicators];
                next[i] = e.target.value;
                setSuccessIndicators(client.id, next);
              }}
            />
          ))}
        </div>
      </div>
    </div>
  );
}

function KrCard({
  kr, accent, duration, onChange, onRemove, hasAdsData,
}: {
  kr: KeyResult;
  accent: string;
  duration: number;
  onChange: (patch: Partial<KeyResult>) => void;
  onRemove: () => void;
  hasAdsData: boolean;
}) {
  const [linkModalOpen, setLinkModalOpen] = useState(false);

  const progress = kr.targetValue !== kr.initialValue
    ? Math.max(0, Math.min(100, ((kr.currentValue - kr.initialValue) / (kr.targetValue - kr.initialValue)) * 100))
    : 0;

  const linkedLabel = kr.linkedToMetric ? AD_METRIC_LABEL[kr.linkedToMetric] : null;
  const hasRealData = !!(kr.linkedToMetric && hasAdsData);

  // Genera línea de proyección lineal del valor inicial al objetivo
  const projectionData = Array.from({ length: duration }).map((_, i) => {
    const frac = (i + 1) / duration;
    const projected = kr.initialValue + (kr.targetValue - kr.initialValue) * frac;
    const actual = kr.monthlyActuals?.[i];
    return { month: `M${i + 1}`, projected: Math.round(projected * 100) / 100, actual };
  });
  const showActuals = (kr.monthlyActuals?.length ?? 0) > 0;

  return (
    <div className="rounded-[10px] border border-border-subtle bg-bg-base/30 p-3">
      {/* Header */}
      <div className="flex items-start gap-3 mb-3">
        <div
          className="h-7 w-7 rounded-md flex items-center justify-center text-xs font-bold shrink-0"
          style={{ background: withAlpha(accent, 0.12), color: accent }}
        >
          KR
        </div>
        <div className="flex-1 min-w-0">
          {/* Descripción full-width sin truncar */}
          <input
            value={kr.description}
            onChange={(e) => onChange({ description: e.target.value })}
            placeholder="Descripción del Key Result"
            className="w-full bg-bg-elevated/40 border border-border-subtle rounded-md px-3 py-2 text-sm text-text-primary outline-none focus:border-accent-violet/60"
            style={{ caretColor: accent }}
          />
          {linkedLabel && (
            <div className="mt-2">
              <span
                className="inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider"
                style={{
                  background: hasRealData ? 'rgba(16,185,129,0.12)' : 'rgba(160,160,180,0.12)',
                  color: hasRealData ? '#10B981' : '#A0A0B4',
                  border: `1px solid ${hasRealData ? 'rgba(16,185,129,0.3)' : 'rgba(160,160,180,0.3)'}`,
                }}
              >
                <Link2 className="h-2.5 w-2.5" /> Vinculado a {linkedLabel}
              </span>
            </div>
          )}
        </div>
        <button
          onClick={onRemove}
          className="h-9 w-9 rounded-md text-text-muted hover:text-status-danger hover:bg-bg-elevated"
          aria-label="Eliminar"
        >
          <Trash2 className="h-4 w-4 mx-auto" />
        </button>
      </div>

      {/* Valores y acción */}
      <div className="grid grid-cols-1 md:grid-cols-5 gap-2 mb-3">
        <Input label="Inicial" type="number" value={kr.initialValue} onChange={(e) => onChange({ initialValue: Number(e.target.value) })} />
        <div>
          <label className="text-xs font-medium text-text-secondary mb-1.5 block">Actual</label>
          {hasRealData ? (
            <div className="h-10 rounded-md border bg-bg-elevated/40 px-3 flex items-center text-sm" style={{ borderColor: 'rgba(16,185,129,0.4)' }}>
              <span className="text-status-success">{kr.currentValue}</span>
            </div>
          ) : kr.linkedToMetric ? (
            <div className="h-10 rounded-md border border-border-subtle bg-bg-base/30 px-3 flex items-center text-sm text-text-muted italic">
              Sin datos aún
            </div>
          ) : (
            <input
              type="number"
              value={kr.currentValue}
              onChange={(e) => onChange({ currentValue: Number(e.target.value) })}
              className="w-full h-10 rounded-md border border-border-subtle bg-bg-surface px-3 text-sm text-text-primary outline-none focus:border-accent-violet/60"
            />
          )}
        </div>
        <Input label="Meta" type="number" value={kr.targetValue} onChange={(e) => onChange({ targetValue: Number(e.target.value) })} />
        <Select label="Unidad" value={kr.unit} options={[
          { value: 'USD', label: 'USD' }, { value: '%', label: '%' }, { value: 'count', label: 'Conteo' }, { value: 'ROAS', label: 'ROAS' },
        ]} onChange={(e) => onChange({ unit: e.target.value as KeyResult['unit'] })} />
        <div>
          <div className="text-xs font-medium text-text-secondary mb-1.5">Acción</div>
          <button
            onClick={() => setLinkModalOpen(true)}
            className="w-full h-10 rounded-md border border-border-subtle text-xs text-text-secondary hover:text-text-primary hover:bg-bg-elevated inline-flex items-center justify-center gap-1"
            title="Vincular a métrica del módulo ADS"
          >
            <Link2 className="h-3.5 w-3.5" /> {kr.linkedToMetric ? 'Cambiar' : 'Vincular ADS'}
          </button>
        </div>
      </div>

      {/* Progreso */}
      <div className="h-2 rounded-full bg-bg-elevated overflow-hidden">
        <div
          className="h-full rounded-full"
          style={{ width: `${progress}%`, background: `linear-gradient(90deg, ${accent}, ${withAlpha(accent, 0.5)})` }}
        />
      </div>
      <div className="text-[10px] text-text-muted text-right mt-1">{progress.toFixed(0)}% completado</div>

      {/* Mini-gráfica proyectado vs real (solo si hay KR vinculado) */}
      {kr.linkedToMetric && (
        <div className="mt-3 rounded-md border border-border-subtle bg-bg-base/20 p-2">
          <div className="flex items-center justify-between mb-1">
            <span className="text-[10px] uppercase tracking-wider text-text-muted">Proyectado vs Real</span>
            {!showActuals && (
              <span className="text-[10px] text-text-muted italic">
                Agrega datos reales en módulo Métricas
              </span>
            )}
          </div>
          <div className="h-20">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={projectionData}>
                <XAxis dataKey="month" hide />
                <YAxis hide />
                <RTooltip
                  content={({ active, payload, label }) => {
                    if (!active || !payload || !payload.length) return null;
                    return (
                      <div className="text-[10px] rounded-md px-2 py-1" style={{ background: 'rgba(15,15,25,0.95)', border: `1px solid ${accent}`, color: '#FFFFFF' }}>
                        <div className="font-semibold mb-0.5">{label}</div>
                        {payload.map((p) => (
                          <div key={p.dataKey} className="flex justify-between gap-3">
                            <span style={{ color: p.color as string }}>{p.dataKey === 'projected' ? 'Proyectado' : 'Real'}</span>
                            <span>{p.value !== null && p.value !== undefined ? Number(p.value).toFixed(2) : '—'}</span>
                          </div>
                        ))}
                      </div>
                    );
                  }}
                />
                <Line type="monotone" dataKey="projected" stroke={withAlpha(accent, 0.55)} strokeWidth={1.5} strokeDasharray="4 4" dot={false} />
                {showActuals && <Line type="monotone" dataKey="actual" stroke={accent} strokeWidth={2} dot={{ r: 2 }} />}
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>
      )}

      {linkModalOpen && (
        <Modal
          open
          onClose={() => setLinkModalOpen(false)}
          size="sm"
          title="Vincular métrica de ADS"
          footer={
            <>
              <Button variant="ghost" size="sm" onClick={() => setLinkModalOpen(false)}>Cancelar</Button>
              {kr.linkedToMetric && (
                <Button variant="danger" size="sm" onClick={() => { onChange({ linkedToMetric: undefined }); setLinkModalOpen(false); toast.info('KR desvinculado'); }}>
                  Desvincular
                </Button>
              )}
            </>
          }
        >
          <p className="text-sm text-text-secondary mb-3">¿Qué métrica de ADS representa este KR?</p>
          <div className="grid grid-cols-2 gap-2">
            {(Object.keys(AD_METRIC_LABEL) as AdMetricKind[]).map((m) => (
              <button
                key={m}
                onClick={() => { onChange({ linkedToMetric: m }); setLinkModalOpen(false); toast.success(`Vinculado a ${AD_METRIC_LABEL[m]}`); }}
                className={cn(
                  'rounded-md border px-3 py-2 text-sm text-left transition',
                  kr.linkedToMetric === m
                    ? 'border-accent-violet/50 bg-accent-violet/10 text-text-primary'
                    : 'border-border-subtle bg-bg-elevated/30 text-text-secondary hover:text-text-primary hover:bg-bg-elevated',
                )}
              >
                {AD_METRIC_LABEL[m]}
              </button>
            ))}
          </div>
        </Modal>
      )}
    </div>
  );
}

const AD_METRIC_LABEL: Record<AdMetricKind, string> = {
  roas: 'ROAS',
  cpl: 'CPL',
  cpc: 'CPC',
  ctr: 'CTR',
  leads: 'Leads totales',
  sales: 'Ventas',
  revenue: 'Facturación',
  spend: 'Inversión',
  reach: 'Alcance',
  other: 'Otro (manual)',
};

/* ═══════════════════════════════════════════════════════════════════════════
   F — INVERSIÓN
   ═══════════════════════════════════════════════════════════════════════════ */

const INV_COLORS = ['#6366F1', '#8B5CF6', '#06B6D4', '#10B981', '#F59E0B', '#EF4444', '#A78BFA', '#34D399', '#F97316', '#EC4899'];

function InvestmentSection({ client, accent }: { client: Client; accent: string }) {
  const state = useProjectionStore((s) => s.states[client.id]);
  const setInvestment = useProjectionStore((s) => s.setInvestment);
  const setDuration = useProjectionStore((s) => s.setDuration);
  const lines = state.investment;

  const totalMonthly = lines.reduce((s, l) => s + l.monthly, 0);
  const totalProject = lines.reduce((sum, l) => {
    const months = l.onlyMonths ? l.onlyMonths.length : state.durationMonths;
    return sum + l.monthly * months;
  }, 0);
  const outputs = calculateFunnel(state.funnel);
  const projectedRevenue = outputs.revenue * state.durationMonths;
  const roi = totalProject > 0 ? projectedRevenue / totalProject : 0;
  const adsInvestment = lines
    .filter((l) => /ads|meta|google|tiktok/i.test(l.category))
    .reduce((s, l) => s + l.monthly * (l.onlyMonths?.length ?? state.durationMonths), 0);
  const projectedRoas = adsInvestment > 0 ? projectedRevenue / adsInvestment : 0;
  const profit = projectedRevenue - totalProject;
  const avgMonthly = state.durationMonths > 0 ? totalProject / state.durationMonths : 0;

  const pieData = lines.map((l) => ({ name: l.category, value: l.monthly }));

  const updateLine = (id: string, patch: Partial<InvestmentLine>) => {
    setInvestment(client.id, lines.map((l) => (l.id === id ? { ...l, ...patch } : l)));
  };
  const addLine = () => {
    setInvestment(client.id, [
      ...lines,
      { id: `i_${Math.random().toString(36).slice(2, 6)}`, category: 'Nueva categoría', monthly: 0 },
    ]);
  };
  const removeLine = (id: string) => {
    setInvestment(client.id, lines.filter((l) => l.id !== id));
  };

  // Stacked bar data por mes
  const stackedData = Array.from({ length: state.durationMonths }).map((_, i) => {
    const monthIdx = i + 1;
    const row: Record<string, string | number> = { month: `M${monthIdx}` };
    let total = 0;
    for (const l of lines) {
      const active = !l.onlyMonths || l.onlyMonths.includes(monthIdx);
      row[l.category] = active ? l.monthly : 0;
      if (active) total += l.monthly;
    }
    row['__total'] = total;
    return row;
  });

  const monthlyTotals = stackedData.map((d) => d['__total'] as number);

  return (
    <div className="space-y-4">
      {/* Top: lista editable + donut */}
      <div className="grid grid-cols-1 lg:grid-cols-[1.4fr_1fr] gap-4">
        <div className="surface p-5">
          <header className="flex items-center justify-between mb-3">
            <h3 className="heading text-base font-bold">Inversión mensual desglosada</h3>
            <div className="flex items-center gap-2">
              <Input
                type="number"
                label="Meses del proyecto"
                value={state.durationMonths}
                onChange={(e) => setDuration(client.id, Math.max(1, Number(e.target.value)))}
                className="w-32"
              />
              <Button size="sm" variant="secondary" leftIcon={<Plus className="h-3.5 w-3.5" />} onClick={addLine}>
                Agregar línea
              </Button>
            </div>
          </header>
          <div className="space-y-2">
            {lines.map((l) => (
              <div key={l.id} className="grid grid-cols-[1.5fr_120px_auto] gap-2 items-center">
                <Input value={l.category} onChange={(e) => updateLine(l.id, { category: e.target.value })} />
                <Input
                  type="number"
                  value={l.monthly}
                  onChange={(e) => updateLine(l.id, { monthly: Number(e.target.value) })}
                  leftAdornment="$"
                />
                <button
                  onClick={() => removeLine(l.id)}
                  className="h-10 w-10 rounded-md text-text-muted hover:text-status-danger hover:bg-bg-elevated"
                  aria-label="Eliminar"
                >
                  <Trash2 className="h-4 w-4 mx-auto" />
                </button>
              </div>
            ))}
          </div>
        </div>

        <div className="surface p-5">
          <h3 className="heading text-base font-bold mb-3">% por categoría</h3>
          <div className="h-72">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie data={pieData} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={88} innerRadius={48}>
                  {pieData.map((_, i) => <Cell key={i} fill={INV_COLORS[i % INV_COLORS.length]} />)}
                </Pie>
                <RTooltip
                  content={({ active, payload }) => {
                    if (!active || !payload || !payload.length) return null;
                    const p = payload[0];
                    const pct = totalMonthly > 0 ? ((p.value as number) / totalMonthly) * 100 : 0;
                    return (
                      <div
                        className="text-xs px-3 py-2 rounded-md"
                        style={{
                          background: 'rgba(15,15,25,0.95)',
                          border: `1px solid ${accent}`,
                          color: '#FFFFFF',
                        }}
                      >
                        <strong>{p.name}</strong>: {formatCurrency(p.value as number)} ({pct.toFixed(1)}%)
                      </div>
                    );
                  }}
                />
                <Legend wrapperStyle={{ fontSize: 10, color: '#A0A0B4' }} />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* Cards resumen */}
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-3">
        <SummaryCard label="Inversión mensual promedio" value={formatCurrency(avgMonthly)} accent={accent} />
        <SummaryCard label="Inversión total del proyecto" value={formatCurrency(totalProject)} accent={accent} />
        <SummaryCard label="Facturación proyectada total" value={formatCurrency(projectedRevenue)} accent={accent} />
        <SummaryCard label="ROI estimado" value={`${roi.toFixed(2)}x`} accent={accent} highlight />
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        <SecondaryCard
          label="ROAS proyectado (solo ADS)"
          hint={`Facturación / inversión en ADS (${formatCurrency(adsInvestment)})`}
          value={`${projectedRoas.toFixed(2)}x`}
          positive={projectedRoas >= 2.5}
        />
        <SecondaryCard
          label="Ganancia estimada"
          hint="Facturación proyectada − inversión total del proyecto"
          value={formatCurrency(profit)}
          positive={profit > 0}
        />
      </div>

      {/* Stacked bar chart + tendencia */}
      <div className="surface p-5">
        <header className="mb-3">
          <h3 className="heading text-base font-bold">Inversión por mes</h3>
          <p className="text-[11px] text-text-muted">Barras apiladas por categoría + línea de tendencia del total mensual</p>
        </header>
        <div className="h-80">
          <ResponsiveContainer width="100%" height="100%">
            <ComposedChart data={stackedData}>
              <CartesianGrid stroke="rgba(255,255,255,0.06)" strokeDasharray="3 3" />
              <XAxis dataKey="month" stroke="#6B6B80" fontSize={11} />
              <YAxis stroke="#6B6B80" fontSize={11} />
              <RTooltip
                content={({ active, payload, label }) => {
                  if (!active || !payload || !payload.length) return null;
                  const total = payload.reduce((s, p) => s + (typeof p.value === 'number' ? p.value : 0), 0);
                  return (
                    <div
                      className="text-xs rounded-md px-3 py-2"
                      style={{ background: 'rgba(15,15,25,0.95)', border: `1px solid ${accent}`, color: '#FFFFFF', minWidth: 200 }}
                    >
                      <div className="font-semibold mb-1.5">{label}</div>
                      {payload
                        .filter((p) => p.dataKey !== '__total' && typeof p.value === 'number' && (p.value as number) > 0)
                        .map((p) => (
                          <div key={p.dataKey} className="flex items-center justify-between gap-3">
                            <span style={{ color: p.color as string }}>● {p.name}</span>
                            <span>{formatCurrency(p.value as number)}</span>
                          </div>
                        ))}
                      <div className="mt-1.5 pt-1.5 border-t border-white/15 flex justify-between font-semibold">
                        <span>Total</span><span style={{ color: accent }}>{formatCurrency(total - (total / 2 > 0 ? 0 : 0))}</span>
                      </div>
                    </div>
                  );
                }}
              />
              <Legend wrapperStyle={{ fontSize: 10, color: '#A0A0B4' }} />
              {lines.map((l, i) => (
                <Bar key={l.id} dataKey={l.category} stackId="inv" fill={INV_COLORS[i % INV_COLORS.length]} />
              ))}
              <Line type="monotone" dataKey="__total" stroke={accent} strokeWidth={2} dot={{ r: 3 }} name="Total mensual" />
            </ComposedChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Tabla con totales por mes y por categoría */}
      <div className="surface p-5">
        <h3 className="heading text-base font-bold mb-3">Resumen por mes con totales</h3>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-[10px] uppercase tracking-wider text-text-muted border-b border-border-default bg-bg-elevated/40">
                <th className="py-2 pr-3 pl-2">Categoría</th>
                {Array.from({ length: state.durationMonths }).map((_, i) => (
                  <th key={i} className="py-2 px-2 text-right">M{i + 1}</th>
                ))}
                <th className="py-2 pl-3 pr-2 text-right" style={{ color: accent }}>Total</th>
              </tr>
            </thead>
            <tbody>
              {lines.map((l, idx) => {
                const rowTotal = Array.from({ length: state.durationMonths }).reduce<number>((sum, _, i) => {
                  const active = !l.onlyMonths || l.onlyMonths.includes(i + 1);
                  return sum + (active ? l.monthly : 0);
                }, 0);
                return (
                  <tr key={l.id} className={cn('border-b border-border-subtle/40', idx % 2 === 1 && 'bg-bg-elevated/15')}>
                    <td className="py-2 pr-3 pl-2 text-text-primary text-xs">
                      <span className="inline-block h-2 w-2 rounded-full mr-2" style={{ background: INV_COLORS[idx % INV_COLORS.length] }} />
                      {l.category}
                    </td>
                    {Array.from({ length: state.durationMonths }).map((_, i) => {
                      const active = !l.onlyMonths || l.onlyMonths.includes(i + 1);
                      return (
                        <td key={i} className={cn('py-2 px-2 text-right text-xs', active ? 'text-text-primary' : 'text-text-muted opacity-40')}>
                          {active ? formatCurrency(l.monthly) : '—'}
                        </td>
                      );
                    })}
                    <td className="py-2 pl-3 pr-2 text-right text-xs font-semibold" style={{ color: accent }}>
                      {formatCurrency(rowTotal)}
                    </td>
                  </tr>
                );
              })}
              {/* Fila TOTAL MES */}
              <tr className="border-t-2 font-bold" style={{ background: withAlpha(accent, 0.10), borderColor: withAlpha(accent, 0.35) }}>
                <td className="py-2.5 pr-3 pl-2 text-text-primary uppercase text-[10px] tracking-wider">Total mes</td>
                {monthlyTotals.map((t, i) => (
                  <td key={i} className="py-2.5 px-2 text-right text-xs text-text-primary">{formatCurrency(t)}</td>
                ))}
                <td className="py-2.5 pl-3 pr-2 text-right text-xs" style={{ color: accent }}>
                  {formatCurrency(totalProject)}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

function SummaryCard({ label, value, accent, highlight }: { label: string; value: string; accent: string; highlight?: boolean }) {
  return (
    <div
      className="surface p-4"
      style={highlight ? { borderColor: withAlpha(accent, 0.35), boxShadow: `0 0 24px -10px ${accent}` } : undefined}
    >
      <div className="text-[10px] uppercase tracking-wider text-text-muted">{label}</div>
      <div className="kpi-number mt-1.5" style={highlight ? { color: accent } : undefined}>{value}</div>
    </div>
  );
}

function SecondaryCard({ label, hint, value, positive }: { label: string; hint: string; value: string; positive: boolean }) {
  const color = positive ? '#10B981' : '#EF4444';
  return (
    <div className="surface p-4" style={{ borderColor: `${color}55` }}>
      <div className="text-[10px] uppercase tracking-wider text-text-muted">{label}</div>
      <div className="text-2xl font-bold mt-1" style={{ color }}>{value}</div>
      <div className="text-[10px] text-text-muted mt-1">{hint}</div>
    </div>
  );
}


/* ═══════════════════════════════════════════════════════════════════════════
   G — DEBRIEFING
   ═══════════════════════════════════════════════════════════════════════════ */

const DEBRIEF_SECTIONS: Array<{ id: keyof import('@/types/projection').DebriefingSections; title: string }> = [
  { id: 'executiveSummary', title: '01. Resumen ejecutivo' },
  { id: 'context',          title: '02. Contexto y situación actual' },
  { id: 'idealClient',      title: '03. El cliente ideal' },
  { id: 'valueProp',        title: '04. Propuesta de valor y oferta' },
  { id: 'communication',    title: '05. Estrategia de comunicación' },
  { id: 'salesSystem',      title: '06. Sistema de ventas' },
  { id: 'successMetrics',   title: '07. Métricas de éxito' },
  { id: 'team',             title: '08. Equipo y responsabilidades' },
  { id: 'timeline',         title: '09. Timeline y próximos pasos' },
  { id: 'agreements',       title: '10. Acuerdos y compromisos' },
  { id: 'appendices',       title: '11. Apéndices' },
];

function DebriefingSection({ client, accent }: { client: Client; accent: string }) {
  const state = useProjectionStore((s) => s.states[client.id]);
  const patch = useProjectionStore((s) => s.patchDebriefing);
  const debrief = state.debriefing;
  const [exporting, setExporting] = useState(false);

  const completedCount = DEBRIEF_SECTIONS.filter((s) => sectionHasContent(debrief[s.id])).length;

  const handleExportDebrief = async () => {
    setExporting(true);
    try {
      await exportDebriefingToPdf({ client, state });
      toast.success('Debriefing PDF descargado');
    } catch (e) {
      console.error(e);
      toast.error('No pudimos generar el PDF');
    } finally {
      setExporting(false);
    }
  };

  return (
    <div className="space-y-4">
      <div className="surface p-5">
        <header className="flex items-center justify-between mb-3 gap-3 flex-wrap">
          <div>
            <h3 className="heading text-base font-bold">Debriefing del proyecto</h3>
            <p className="text-[11px] text-text-muted">{completedCount} de {DEBRIEF_SECTIONS.length} secciones completadas</p>
          </div>
          <div className="flex items-center gap-3">
            <div className="w-48 h-2 rounded-full bg-bg-elevated overflow-hidden">
              <div
                className="h-full rounded-full"
                style={{ width: `${(completedCount / DEBRIEF_SECTIONS.length) * 100}%`, background: accent }}
              />
            </div>
            <Button size="sm" leftIcon={<Download className="h-3.5 w-3.5" />} loading={exporting} onClick={handleExportDebrief}>
              Descargar PDF
            </Button>
          </div>
        </header>
      </div>

<ResultsPanel client={client} accent={accent} />

      {DEBRIEF_SECTIONS.map((s) => (
        <DebriefingItem
          key={s.id}
          title={s.title}
          accent={accent}
          sectionKey={s.id}
          client={client}
          value={debrief[s.id]}
          onChange={(v) => patch(client.id, { [s.id]: v } as never)}
        />
      ))}
    </div>
  );
}

function ResultsPanel({ client, accent }: { client: Client; accent: string }) {
  const state = useProjectionStore((s) => s.states[client.id]);
  const outputs = calculateFunnel(state.funnel);
  const totalInvestment = state.investment.reduce((s, l) => s + l.monthly * (l.onlyMonths?.length ?? state.durationMonths), 0);
  const adsInvestment = state.investment
    .filter((l) => /ads|meta|google|tiktok/i.test(l.category))
    .reduce((s, l) => s + l.monthly * (l.onlyMonths?.length ?? state.durationMonths), 0);

  // "Real" se llenará desde el módulo Métricas cuando haya datos. Por ahora null.
  type Row = { label: string; projected: string; real: string | null; bold?: boolean; isRoas?: boolean };
  const rows: Row[] = [
    { label: 'Valor Inversión Total',              projected: `$${totalInvestment.toLocaleString()}`, real: null },
    { label: 'Inversión en Captación (ADS)',       projected: `$${adsInvestment.toLocaleString()}`, real: null },
    { label: 'CPL (Costo por Lead)',               projected: `$${outputs.cpl}`, real: null },
    { label: 'Tasa de Conversión Landing',         projected: `${(state.funnel.landingConversionRate * 100).toFixed(2)}%`, real: null },
    { label: 'No. de Leads Totales',               projected: `${(outputs.leads * state.durationMonths).toLocaleString()}`, real: null },
    { label: 'Tasa de Entrada WhatsApp/CRM',       projected: '80%', real: null },
    { label: 'Contactos Calificados',              projected: `${(outputs.sqls * state.durationMonths).toLocaleString()}`, real: null },
    { label: '% Asistencia a Evento/Demo',         projected: '60%', real: null },
    { label: 'Tasa de Cierre',                     projected: `${(state.funnel.closeRate * 100).toFixed(0)}%`, real: null },
    { label: 'Ventas Totales',                     projected: `${(outputs.sales * state.durationMonths).toLocaleString()}`, real: null },
    { label: 'Ticket Promedio',                    projected: `$${state.funnel.averageTicket.toLocaleString()}`, real: null },
    { label: 'FACTURACIÓN TOTAL',                  projected: `$${(outputs.revenue * state.durationMonths).toLocaleString()}`, real: null, bold: true },
    { label: 'ROAS',                               projected: `${outputs.roas}x`, real: null, bold: true, isRoas: true },
  ];

  return (
    <div className="surface p-5 mb-3">
      <header className="mb-3">
        <h3 className="heading text-base font-bold">Panel de Resultados</h3>
        <p className="text-[11px] text-text-muted">Proyectado vs Real — los valores reales se llenan automáticamente cuando hay datos en el módulo Métricas</p>
      </header>
      <div className="overflow-x-auto rounded-[10px] border border-border-subtle bg-[#FAFBFD]">
        <table className="w-full text-sm">
          <thead>
            <tr style={{ background: accent, color: '#FFFFFF' }} className="text-left text-[11px] uppercase tracking-wider">
              <th className="py-2.5 pl-4 pr-3">Métrica</th>
              <th className="py-2.5 pr-3 text-right">Proyectado</th>
              <th className="py-2.5 pr-4 text-right">Real</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((r, idx) => {
              const noReal = r.real === null;
              const realBelowProj = !noReal && r.real !== null && (r.real < r.projected); // simple string compare; conceptual
              const bgRow = r.bold
                ? '#FFFFFF'
                : noReal
                ? (idx % 2 === 0 ? '#FFFFFF' : '#F3F8F3')
                : realBelowProj ? '#FEE2E2' : '#D1FAE5';
              return (
                <tr key={r.label} style={{ background: bgRow }} className="border-b border-gray-200">
                  <td className={cn('py-2.5 pl-4 pr-3 text-gray-800', r.bold && 'font-bold')}>{r.label}</td>
                  <td className={cn('py-2.5 pr-3 text-right text-gray-900', r.bold && 'font-bold')}>{r.projected}</td>
                  <td className="py-2.5 pr-4 text-right text-gray-500 italic">{r.real ?? 'Pendiente'}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* Card destacada ROAS */}
      <div
        className="mt-4 rounded-[14px] p-6 text-center"
        style={{
          background: `linear-gradient(135deg, ${withAlpha(accent, 0.18)}, ${withAlpha(accent, 0.06)})`,
          border: `1px solid ${withAlpha(accent, 0.35)}`,
          boxShadow: `0 0 28px -12px ${accent}`,
        }}
      >
        <div className="text-[11px] uppercase tracking-wider text-text-muted">ROAS</div>
        <div className="heading text-5xl font-extrabold mt-1" style={{ color: accent }}>
          {outputs.roas}x
        </div>
        <div className="text-[11px] text-text-muted mt-2">Retorno de la inversión publicitaria proyectada</div>
      </div>
    </div>
  );
}

function sectionHasContent(v: unknown): boolean {
  if (!v || typeof v !== 'object') return false;
  return Object.values(v as Record<string, unknown>).some((x) => {
    if (typeof x === 'string') return x.trim().length > 0;
    if (Array.isArray(x)) return x.length > 0;
    return false;
  });
}

function DebriefingItem({
  title, accent, sectionKey, client, value, onChange,
}: {
  title: string;
  accent: string;
  sectionKey: keyof import('@/types/projection').DebriefingSections;
  client: Client;
  value: unknown;
  onChange: (v: unknown) => void;
}) {
  const [expanded, setExpanded] = useState(false);
  const hasContent = sectionHasContent(value);
  const isAutoGen = (value as { autoGenerated?: boolean } | undefined)?.autoGenerated === true;

  const generateAi = async () => {
    await new Promise((r) => setTimeout(r, 800));
    const generators: Partial<Record<keyof import('@/types/projection').DebriefingSections, unknown>> = {
      executiveSummary: { text: client.aiBrainData.executiveSummary ?? `${client.name} apunta a construir un sistema de adquisición rentable en su sector (${client.industry}).`, autoGenerated: true },
      idealClient: { text: (client.onboardingData.audience as { idealClientDescription?: string } | undefined)?.idealClientDescription ?? 'Pendiente describir avatar.', autoGenerated: true },
      valueProp: { text: client.aiBrainData.irresistibleOffer ?? 'Pendiente definir.', bigIdea: '', guarantees: '' },
    };
    if (generators[sectionKey]) {
      onChange(generators[sectionKey]);
      toast.success('Sección generada con IA');
    } else {
      toast.info('Generación IA disponible próximamente para esta sección.');
    }
  };

  return (
    <section className="surface overflow-hidden">
      <header
        onClick={() => setExpanded(!expanded)}
        className="flex items-center justify-between gap-3 px-5 py-3.5 cursor-pointer hover:bg-bg-elevated/30"
      >
        <div className="flex items-center gap-3 min-w-0">
          <h4 className="heading text-sm font-bold truncate">{title}</h4>
          {hasContent && <Badge tone="success"><Check className="h-2.5 w-2.5" /></Badge>}
          {isAutoGen && <Badge tone="info">Auto-generado</Badge>}
        </div>
        {expanded ? <ChevronUp className="h-4 w-4 text-text-muted" /> : <ChevronDown className="h-4 w-4 text-text-muted" />}
      </header>
      {expanded && (
        <div className="border-t border-border-subtle p-5 space-y-3">
          {sectionKey === 'executiveSummary' || sectionKey === 'idealClient' ? (
            <Textarea
              rows={5}
              value={(value as { text?: string } | undefined)?.text ?? ''}
              onChange={(e) => onChange({ text: e.target.value, autoGenerated: false })}
            />
          ) : sectionKey === 'context' ? (
            <ContextEditor value={value as never} onChange={onChange} />
          ) : sectionKey === 'valueProp' ? (
            <ValuePropEditor value={value as never} onChange={onChange} />
          ) : sectionKey === 'communication' ? (
            <CommunicationEditor value={value as never} onChange={onChange} />
          ) : sectionKey === 'salesSystem' ? (
            <SalesSystemEditor value={value as never} onChange={onChange} client={client} />
          ) : sectionKey === 'successMetrics' ? (
            <SuccessMetricsEditor value={value as never} onChange={onChange} />
          ) : sectionKey === 'team' ? (
            <TeamRaciEditor value={value as never} onChange={onChange} />
          ) : sectionKey === 'timeline' ? (
            <TimelineEditor value={value as never} onChange={onChange} />
          ) : sectionKey === 'agreements' ? (
            <AgreementsEditor value={value as never} onChange={onChange} />
          ) : sectionKey === 'appendices' ? (
            <AppendicesEditor value={value as never} onChange={onChange} />
          ) : null}

          {(sectionKey === 'executiveSummary' || sectionKey === 'idealClient' || sectionKey === 'valueProp') && (
            <Button size="sm" variant="secondary" leftIcon={<Sparkles className="h-3.5 w-3.5" />} onClick={generateAi}>
              Generar con IA
            </Button>
          )}
        </div>
      )}
    </section>
  );
}

/* ─── Editores por sub-sección ─── */

function ContextEditor({ value, onChange }: { value?: { situation?: string; challenges?: string; opportunities?: string; swot?: { s?: string; w?: string; o?: string; t?: string } }; onChange: (v: unknown) => void }) {
  const v = value ?? {};
  const swot = v.swot ?? {};
  const set = (patch: typeof v) => onChange({ ...v, ...patch });
  return (
    <div className="space-y-3">
      <Textarea label="Situación del cliente antes del proyecto" rows={3} value={v.situation ?? ''} onChange={(e) => set({ situation: e.target.value })} />
      <Textarea label="Principales desafíos" rows={3} value={v.challenges ?? ''} onChange={(e) => set({ challenges: e.target.value })} />
      <Textarea label="Oportunidades detectadas" rows={3} value={v.opportunities ?? ''} onChange={(e) => set({ opportunities: e.target.value })} />
      <div className="text-[10px] uppercase tracking-wider text-text-muted mt-2">Análisis FODA</div>
      <div className="grid grid-cols-2 gap-2">
        <Textarea label="Fortalezas" rows={2} value={swot.s ?? ''} onChange={(e) => set({ swot: { ...swot, s: e.target.value } })} />
        <Textarea label="Debilidades" rows={2} value={swot.w ?? ''} onChange={(e) => set({ swot: { ...swot, w: e.target.value } })} />
        <Textarea label="Oportunidades" rows={2} value={swot.o ?? ''} onChange={(e) => set({ swot: { ...swot, o: e.target.value } })} />
        <Textarea label="Amenazas" rows={2} value={swot.t ?? ''} onChange={(e) => set({ swot: { ...swot, t: e.target.value } })} />
      </div>
    </div>
  );
}

function ValuePropEditor({ value, onChange }: { value?: { text?: string; bigIdea?: string; guarantees?: string }; onChange: (v: unknown) => void }) {
  const v = value ?? {};
  return (
    <div className="space-y-3">
      <Textarea label="Oferta irresistible" rows={4} value={v.text ?? ''} onChange={(e) => onChange({ ...v, text: e.target.value })} />
      <Textarea label="The Big Idea (mensaje central)" rows={2} value={v.bigIdea ?? ''} onChange={(e) => onChange({ ...v, bigIdea: e.target.value })} />
      <Textarea label="Garantías / elementos que reducen riesgo" rows={3} value={v.guarantees ?? ''} onChange={(e) => onChange({ ...v, guarantees: e.target.value })} />
    </div>
  );
}

function CommunicationEditor({ value, onChange }: { value?: { text?: string; tone?: string; angles?: string[] }; onChange: (v: unknown) => void }) {
  const v = value ?? {};
  const angles = v.angles ?? [];
  return (
    <div className="space-y-3">
      <Textarea label="Narrativa de marca resumida" rows={3} value={v.text ?? ''} onChange={(e) => onChange({ ...v, text: e.target.value })} />
      <Input label="Tono y voz" value={v.tone ?? ''} onChange={(e) => onChange({ ...v, tone: e.target.value })} />
      <Textarea label="Ángulos de comunicación (uno por línea, 5-7)" rows={5}
        value={angles.join('\n')}
        onChange={(e) => onChange({ ...v, angles: e.target.value.split('\n').filter(Boolean).slice(0, 7) })} />
    </div>
  );
}

function SalesSystemEditor({ value, onChange, client }: { value?: { text?: string; funnel?: string; stack?: string }; onChange: (v: unknown) => void; client: Client }) {
  const v = value ?? {};
  return (
    <div className="space-y-3">
      <div className="rounded-[10px] border border-border-subtle bg-bg-base/30 p-3 text-xs text-text-secondary">
        Tipo de sistema actual: <strong className="text-text-primary capitalize">{client.projectType.replace('_', ' ')}</strong>
      </div>
      <Textarea label="Descripción del sistema de ventas" rows={3} value={v.text ?? ''} onChange={(e) => onChange({ ...v, text: e.target.value })} />
      <Textarea label="Funnel completo (paso a paso)" rows={4} value={v.funnel ?? ''} onChange={(e) => onChange({ ...v, funnel: e.target.value })} />
      <Textarea label="Stack de herramientas" rows={3} value={v.stack ?? ''} onChange={(e) => onChange({ ...v, stack: e.target.value })} />
    </div>
  );
}

function SuccessMetricsEditor({ value, onChange }: { value?: { kpis?: Array<{ name: string; frequency: string; owner: string; alertThreshold: string }> }; onChange: (v: unknown) => void }) {
  const kpis = value?.kpis ?? [];
  const update = (i: number, patch: Partial<{ name: string; frequency: string; owner: string; alertThreshold: string }>) =>
    onChange({ kpis: kpis.map((k, idx) => (idx === i ? { ...k, ...patch } : k)) });
  const add = () => onChange({ kpis: [...kpis, { name: '', frequency: '', owner: '', alertThreshold: '' }] });
  const remove = (i: number) => onChange({ kpis: kpis.filter((_, idx) => idx !== i) });
  return (
    <div className="space-y-2">
      {kpis.map((k, i) => (
        <div key={i} className="grid grid-cols-1 md:grid-cols-[1.4fr_1fr_1fr_1.2fr_auto] gap-2 items-end">
          <Input label="KPI" value={k.name} onChange={(e) => update(i, { name: e.target.value })} />
          <Input label="Frecuencia" value={k.frequency} onChange={(e) => update(i, { frequency: e.target.value })} placeholder="semanal / mensual" />
          <Input label="Responsable" value={k.owner} onChange={(e) => update(i, { owner: e.target.value })} />
          <Input label="Umbral de alerta" value={k.alertThreshold} onChange={(e) => update(i, { alertThreshold: e.target.value })} />
          <button onClick={() => remove(i)} className="h-10 w-10 rounded-md text-text-muted hover:text-status-danger hover:bg-bg-elevated">
            <Trash2 className="h-4 w-4 mx-auto" />
          </button>
        </div>
      ))}
      <Button size="sm" variant="secondary" leftIcon={<Plus className="h-3.5 w-3.5" />} onClick={add}>Agregar KPI</Button>
    </div>
  );
}

function TeamRaciEditor({ value, onChange }: { value?: { text?: string; raci?: Array<{ task: string; responsible: string; accountable: string; consulted: string; informed: string }> }; onChange: (v: unknown) => void }) {
  const v = value ?? {};
  const raci = v.raci ?? [];
  const update = (i: number, patch: Partial<typeof raci[number]>) => onChange({ ...v, raci: raci.map((r, idx) => (idx === i ? { ...r, ...patch } : r)) });
  const add = () => onChange({ ...v, raci: [...raci, { task: '', responsible: '', accountable: '', consulted: '', informed: '' }] });
  return (
    <div className="space-y-3">
      <Textarea label="Equipo y responsabilidades clave" rows={3} value={v.text ?? ''} onChange={(e) => onChange({ ...v, text: e.target.value })} />
      <div className="text-[10px] uppercase tracking-wider text-text-muted">Matriz RACI</div>
      {raci.map((r, i) => (
        <div key={i} className="grid grid-cols-5 gap-2">
          <Input placeholder="Tarea / Decisión" value={r.task} onChange={(e) => update(i, { task: e.target.value })} />
          <Input placeholder="Responsable" value={r.responsible} onChange={(e) => update(i, { responsible: e.target.value })} />
          <Input placeholder="Aprobador" value={r.accountable} onChange={(e) => update(i, { accountable: e.target.value })} />
          <Input placeholder="Consultado" value={r.consulted} onChange={(e) => update(i, { consulted: e.target.value })} />
          <Input placeholder="Informado" value={r.informed} onChange={(e) => update(i, { informed: e.target.value })} />
        </div>
      ))}
      <Button size="sm" variant="secondary" leftIcon={<Plus className="h-3.5 w-3.5" />} onClick={add}>Agregar fila RACI</Button>
    </div>
  );
}

function TimelineEditor({ value, onChange }: { value?: { text?: string; nextMilestones?: Array<{ title: string; date: string }> }; onChange: (v: unknown) => void }) {
  const v = value ?? {};
  const ms = v.nextMilestones ?? [];
  const update = (i: number, patch: Partial<typeof ms[number]>) => onChange({ ...v, nextMilestones: ms.map((m, idx) => (idx === i ? { ...m, ...patch } : m)) });
  const add = () => onChange({ ...v, nextMilestones: [...ms, { title: '', date: '' }].slice(0, 3) });
  return (
    <div className="space-y-3">
      <Textarea label="Timeline resumido" rows={3} value={v.text ?? ''} onChange={(e) => onChange({ ...v, text: e.target.value })} />
      <div className="text-[10px] uppercase tracking-wider text-text-muted">Próximos 3 hitos</div>
      {ms.map((m, i) => (
        <div key={i} className="grid grid-cols-[2fr_1fr] gap-2">
          <Input placeholder="Hito" value={m.title} onChange={(e) => update(i, { title: e.target.value })} />
          <Input type="date" value={m.date} onChange={(e) => update(i, { date: e.target.value })} />
        </div>
      ))}
      {ms.length < 3 && <Button size="sm" variant="secondary" leftIcon={<Plus className="h-3.5 w-3.5" />} onClick={add}>Agregar hito</Button>}
    </div>
  );
}

function AgreementsEditor({ value, onChange }: { value?: { agencyDelivers?: string; clientProvides?: string; approvalTimes?: string; conditions?: string }; onChange: (v: unknown) => void }) {
  const v = value ?? {};
  return (
    <div className="space-y-3">
      <Textarea label="La agencia se compromete a entregar" rows={3} value={v.agencyDelivers ?? ''} onChange={(e) => onChange({ ...v, agencyDelivers: e.target.value })} />
      <Textarea label="El cliente se compromete a proveer / aprobar" rows={3} value={v.clientProvides ?? ''} onChange={(e) => onChange({ ...v, clientProvides: e.target.value })} />
      <Input label="Tiempos de aprobación acordados" value={v.approvalTimes ?? ''} onChange={(e) => onChange({ ...v, approvalTimes: e.target.value })} />
      <Textarea label="Condiciones del proyecto" rows={3} value={v.conditions ?? ''} onChange={(e) => onChange({ ...v, conditions: e.target.value })} />
    </div>
  );
}

function AppendicesEditor({ value, onChange }: { value?: { competitorAnalysis?: string; references?: string; techStack?: string; budget?: string }; onChange: (v: unknown) => void }) {
  const v = value ?? {};
  return (
    <div className="space-y-3">
      <Textarea label="Análisis de competencia detallado" rows={3} value={v.competitorAnalysis ?? ''} onChange={(e) => onChange({ ...v, competitorAnalysis: e.target.value })} />
      <Textarea label="Referencias visuales / moodboard (URLs)" rows={2} value={v.references ?? ''} onChange={(e) => onChange({ ...v, references: e.target.value })} />
      <Textarea label="Stack tecnológico recomendado" rows={2} value={v.techStack ?? ''} onChange={(e) => onChange({ ...v, techStack: e.target.value })} />
      <Textarea label="Presupuesto detallado" rows={3} value={v.budget ?? ''} onChange={(e) => onChange({ ...v, budget: e.target.value })} />
    </div>
  );
}
