/**
 * Limpia el texto de una transcripción o unas notas antes de dárselo a la IA.
 *
 * Quita dos cosas que no son contenido de la reunión y que ensucian todo lo que
 * venga después:
 *
 *  1. ENTIDADES HTML sueltas. Los exportadores a markdown dejan `&nbsp;` y
 *     compañía como texto literal. Se vieron el 18-sep al subir unas notas de
 *     Gemini: el campo de notas empezaba con dos líneas que decían "&nbsp;".
 *
 *  2. EL PIE DE PÁGINA DEL EXPORTADOR. Gemini y Meet añaden su propio texto
 *     ("Revisa las notas de Gemini para asegurarte de que sean precisas…"), que
 *     no lo dijo nadie en la reunión. Dejarlo dentro es peor que una molestia:
 *     la IA lo lee como contenido y puede sacar de ahí una "tarea" que consiste
 *     en revisar las notas.
 *
 * NO reescribe nada más. Lo que dijeron las personas se queda exactamente como
 * está: corregirle la gramática a una transcripción es empezar a inventar.
 */

const ENTIDADES: Record<string, string> = {
  '&nbsp;': ' ',
  '&amp;': '&',
  '&lt;': '<',
  '&gt;': '>',
  '&quot;': '"',
  '&#39;': "'",
  '&apos;': "'",
  '&hellip;': '…',
  '&mdash;': '—',
  '&ndash;': '–',
};

/**
 * Coletillas de los exportadores. Se comparan sobre la línea entera en
 * minúsculas: si una línea ES la coletilla, se quita; si la contiene dentro de
 * una frase más larga, se respeta, porque entonces puede que alguien lo dijera.
 */
const COLETILLAS = [
  /^revisa las notas de gemini/i,
  /^obtén sugerencias y descubre cómo gemini toma notas/i,
  /^gemini puede cometer errores/i,
  /^please check important info/i,
  /^review gemini notes for accuracy/i,
  /^get tips and learn how gemini takes notes/i,
  /^esta transcripción fue generada/i,
  /^transcript generated by/i,
];

export function limpiarTextoPegado(crudo: string): string {
  if (!crudo) return '';

  let texto = crudo;
  for (const [entidad, valor] of Object.entries(ENTIDADES)) {
    texto = texto.split(entidad).join(valor);
  }
  // Entidades numéricas (&#8220; y &#x201C;), que son demasiadas para listarlas.
  texto = texto
    .replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(Number(n)))
    .replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCodePoint(parseInt(n, 16)));

  const lineas = texto
    .split('\n')
        // El espacio duro (U+00A0) se escribe como escape: como carácter
    // literal es invisible en el código y nadie sabría qué se está quitando.
    .map((l) => l.replace(/\u00a0/g, ' ').trimEnd())
    .filter((l) => !COLETILLAS.some((re) => re.test(l.trim())));

  return lineas
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}
